@baseUrl = http://localhost:8080

### Login
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "emailUser": "raphael.baroni@vinci.be",
  "password": "Prof24,z"
}

> {%
  client.global.set("userToken", response.body.token);
%}

### Get All Schoolyears
GET {{baseUrl}}/schoolYears
Authorization: {{userToken}}
